import type { Metadata } from "next";
import "../../styles/globals.css";
import Navbar from "@/components/Navbar";
import "slick-carousel/slick/slick.css";
import PageButton from "@/components/PageButton";
import Footer from "@/components/Footer";
import Layout from "@/components/Layout";
import { Toaster } from "react-hot-toast";
export const metadata: Metadata = {
  title: "BENAB",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-display">
       <Layout>
       <Navbar />
        <PageButton/>
        {children}
        <Footer/>
       </Layout>
       <Toaster
          position="bottom-right"
          toastOptions={{
            style: {
              background: "#000",
              fontWeight:"bold",
              color: "#fff",
            },
          }}
        />
      </body>
    </html>
  );
}
